name: Publish PointMint Plugin

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'external/pointmint/**'

jobs:
  build-and-publish:
    runs-on: windows-latest
    if: "!contains(github.ref, 'dev')"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Initialize Koishi Project
      run: |
        npm init koishi@latest --yes
        cd koishi-project
        mkdir external\pointmint
        cp -r ../external/pointmint/* external\pointmint/

    - name: Build Plugin
      run: |
        cd koishi-project
        npm install
        npm run build pointmint

    - name: Publish to NPM
      run: |
        cd koishi-project
        npm run pub pointmint
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
