name: Publish Plugin

on:
  push:
    tags:
      - 'v*[!dev]*'

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: external/pointmint
        run: npm install

      - name: Build plugin
        working-directory: external/pointmint
        run: npm run build

      - name: Publish to npm
        working-directory: external/pointmint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
