name: 构建与发布

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: 安装依赖
        run: npm install
      
      - name: 检查版本
        id: check_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION != *dev* ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: 构建 TypeScript
        if: steps.check_version.outputs.is_release == 'true'
        run: npm run build
      
      - name: 发布到 NPM
        if: steps.check_version.outputs.is_release == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: 创建 GitHub Release
        if: steps.check_version.outputs.is_release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.check_version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
